name: Optimize Nutrition

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy openpyxl

    - name: Run optimization and generate files
      run: |
        # Create recipes directory if it doesn't exist
        mkdir -p recipes

        # Run Python script to generate files
        python app.py

        # Stage all changes including new files in main branch
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A

        # Check if there are any changes to commit to main
        if ! git diff --staged --quiet; then
          git commit -m "Auto-generate new meal plan [skip ci]"
          git push origin main
        fi

    - name: Deploy to GitHub Pages
      run: |
        # Create a temporary directory for gh-pages content
        tmp_dir=$(mktemp -d)

        # Copy HTML files to temp directory, maintaining flat structure
        cp recipes/html/*.html "$tmp_dir/"

        # Switch to gh-pages branch
        git fetch origin gh-pages
        git checkout gh-pages || git checkout -b gh-pages

        # Remove existing HTML files
        rm -f *.html

        # Copy new HTML files from temp directory
        cp "$tmp_dir"/*.html .

        # Stage and commit changes
        git add *.html

        # Check if there are changes to commit
        if ! git diff --staged --quiet; then
          git commit -m "Update GitHub Pages [skip ci]"
          git push origin gh-pages
        fi

        # Clean up
        rm -rf "$tmp_dir"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}