name: Optimize Nutrition

on:
  workflow_dispatch:  # Manual trigger
  # push:
  #   branches:
  #     - main  # or master, depending on your default branch name
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy openpyxl

    - name: Run optimization, commit and push changes
      run: |
        # Configure git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        # Create recipes directory if it doesn't exist
        mkdir -p recipes

        # Run your Python script to generate files
        python app.py

        # Stage all changes including new files
        git add -A

        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        # Commit changes
        git commit -m "Auto-generate new meal plan [skip ci]"

        # Simple push without retry logic
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}